version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # build image
      - run: |
          docker info
          docker build -t aspnetapp -f Dockerfile .
      # deploy the image
      - run: |
          docker login --username=d4n0n-myself --password=6453475d-ba25-46af-b503-2abd00edc01e registry.heroku.com
          docker tag aspnetapp registry.heroku.com/infosystemprod/web
          docker push registry.heroku.com/infosystemprod/web                
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web -a infosystemprod
